vipul:
  jain: 21
logicAppUrl: https://prod-59.eastus.logic.azure.com/workflows/bbbb7fb35d2e4414a76852154562c744/triggers/request/paths/invoke/Vipul?api-version=2016-10-01&sp=%2Ftriggers%2Frequest%2Frun&sv=1.0&sig=bnJoalxV5UI_BpE8PrxcnjYn3_fjUf5A06bzRMo4mCs
spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            endpoint: https://keyvaultvjj.vault.azure.net/